// Site content. Each project becomes /work/<slug>.html and a row in the home page index.
// `cover` is the image used in the index preview; `rows` lay out the project page:
//   'name'            one full-width image
//   ['a', 'b']        two images side by side
//   { video, poster, ratio }   a looping muted clip
// Image names refer to assets/img/<slug>/<name>-<width>.webp (made by src/images.mjs).

export const SITE = {
  name: 'Carl Serafin',
  fullName: 'Carl Paolo Serafin',
  role: 'Graphic designer',
  city: 'Dubai',
  email: 'carlserafin02@gmail.com',
  behance: 'https://www.behance.net/carlserafin',
  url: 'https://cepsmyster.github.io/',
  description: 'Carl Paolo Serafin is a graphic designer in Dubai working on brand identities, print, social media, signage and presentations, and currently exploring web development.',
};

export const ABOUT = {
  intro: [
    'I’m Carl Paolo Serafin, a graphic designer based in Dubai. I’ve always loved art, and design became the way I turn that into work people use: brand identities, company profiles and brochures, social media campaigns, signage and presentations, mostly for real estate, construction and architecture companies in the UAE.',
    'I’m currently exploring web development. The Top Concept International website is the first site I designed and built myself, and I’m learning by making real pages for real clients.',
    'I adapt quickly to new teams and briefs, and I like a project most when the same idea has to hold together across a phone screen, a printed page and a sign on a building.',
  ],
  fields: ['Brand identity', 'Print and editorial', 'Social media', 'Signage', 'Presentations', 'Motion', 'Web design and development'],
  tools: ['Illustrator', 'Photoshop', 'InDesign', 'After Effects', 'Premiere Pro', 'Figma', 'HTML, CSS and JavaScript'],
  languages: ['Filipino', 'English'],
};

export const PROJECTS = [
  {
    slug: 'top-concept-website',
    title: 'Top Concept International website',
    client: 'Top Concept International',
    field: 'Web design and development',
    sector: 'Architecture and engineering',
    year: '2026',
    cover: 'home',
    link: { href: 'https://cepsmyster.github.io/top-concept-website/', label: 'Visit the live site' },
    summary: 'A website I designed and built for an architecture and engineering consultancy in Dubai.',
    body: [
      'The home page opens on a tower drawn as a blueprint on one side and the finished render on the other. Visitors drag the line between them, from concept to completion, while the headline draws itself in outline and fills in.',
      'Behind it sit a filterable project archive with a page for every project, an expertise page, blogs, careers and contact forms, in a dark and a light theme. It’s plain HTML, CSS and JavaScript, hosted on GitHub Pages.',
    ],
    rows: ['home', ['mobile', 'projects'], 'expertise'],
  },
  {
    slug: 'tci-company-profile',
    title: 'Top Concept International company profile',
    client: 'Top Concept International',
    field: 'Brand identity, editorial',
    sector: 'Architecture and engineering',
    year: '2026',
    cover: 'cover',
    summary: 'A 108-page company profile and the identity system it sits on.',
    body: [
      'The profile walks through the group’s architecture, interiors and landscape work. Each discipline opens on a full-bleed divider, and the project spreads that follow use one grid of large and small renders so a hundred pages read as one book.',
      'The identity behind it pairs the TCi wordmark with a folded-square mark, a palette of greys, Montserrat and Inter, and carries through to business cards, wall signage, folders, pens and mugs.',
    ],
    rows: ['cover', ['divider', 'interiors'], 'azizi', ['hospitality', 'rox'], 'lobby', ['interiors2', 'landscape'], 'marks', 'identity'],
  },
  {
    slug: 'touch-id-contracting',
    title: 'Touch ID Contracting brand identity',
    client: 'Touch ID Contracting',
    field: 'Brand identity',
    sector: 'Construction',
    year: '2026',
    cover: 'logo',
    summary: 'Two identity systems for a Dubai contracting company: the touch id wordmark and the tid monogram.',
    body: [
      'The touch id wordmark hides a fingerprint in the o and is set in cinnamon orange with a striped barrier-tape pattern. It runs across business cards, building signage, company cars, buses, mugs and safety vests.',
      'TID condenses the name into a boxed monogram in charcoal and bronze, built for the places a contractor’s name is seen most: uniforms, overalls, helmets, staff IDs and the site bus. Both share one line: building with precision, delivering with confidence.',
    ],
    rows: ['logo', ['mark', 'pattern'], 'cards', ['signage', 'vest'], 'cars', 'bus', 'tid', ['tidcolors', 'tidcards'], ['tidshirt', 'tidhelmet'], 'tidoveralls', ['tidid', 'tidbus']],
  },
  {
    slug: 'ips-2026',
    title: 'IPS 2026 exhibition campaign',
    client: 'The Top Group',
    field: 'Social media, motion',
    sector: 'Exhibition',
    year: '2026',
    cover: 'countdown',
    summary: 'Countdown stories and the booth backdrop video for The Top Group at IPS 2026, Dubai World Trade Centre.',
    body: [
      'The countdown stories keep to one big number, the dates and the booth, with every company in the group signing off underneath: TCI, TCI Interiors, TCI Landscape, X30 Technical, Touch ID Decorations and TID Contracting.',
      'On the stand, the backdrop video cycled through project sheets from across the group, interleaved with vertical reels from their Instagram pages.',
    ],
    rows: [{ video: 'ips-backdrop', ratio: '16 / 9' }, ['countdown', { video: 'villa-reel', ratio: '9 / 16' }]],
  },
  {
    slug: 'oncology-presentation',
    title: 'Oncology infusion center presentation',
    client: 'Touch ID Decoration',
    field: 'Presentation design',
    sector: 'Healthcare interiors',
    year: '2026',
    cover: 'reception',
    summary: 'A client presentation for the renovation of a hospital’s Level 6E oncology infusion center.',
    body: [
      'The deck takes the client from the floor plan of 26 single rooms into 3D concept views of the reception, patient rooms and the details a patient actually touches: bed controls, call buttons, door signs.',
      'I kept the layout quiet, with one white frame and a small header on every slide, so the renders carry the presentation.',
    ],
    rows: ['cover', 'reception', ['ward', 'room'], 'lounge', ['bed', 'door'], 'detail'],
  },
  {
    slug: 'repc-signage',
    title: 'Royal European Polyclinic Academy signage',
    client: 'Royal European Polyclinic Academy',
    field: 'Signage, print',
    sector: 'Healthcare and beauty',
    year: '2026',
    cover: 'navy',
    summary: 'Opening soon and grand opening signage for a polyclinic academy’s new storefront.',
    body: [
      'Two directions for the hoarding: a light one with script lettering and the treatment device as the hero, and a deep navy one built on close-up treatment photography.',
      'Both were mocked up on a photo of the actual storefront before going to print.',
    ],
    rows: ['navy', ['grand', 'soon'], 'navy2', 'site'],
  },
  {
    slug: 'abdulla-al-arif',
    title: 'Abdulla Al Arif Investments',
    client: 'Abdulla Al Arif Investments',
    field: 'Brand system, digital, print',
    sector: 'Diversified industrial group',
    year: '2024–2026',
    cover: 'emails',
    summary: 'One visual identity across a group of construction, real estate and service companies.',
    body: [
      'I developed a unified visual identity for the AAAI Group’s diverse sectors, designing exhibition environments and high-profile print assets for milestones like the Annual Gathering Iftar, and modernising their visual language across construction and real estate.',
      'I created a scalable design system that kept the brand consistent while highlighting the strengths of each subsidiary, from internal email campaigns and Instagram stories to magazines, posters and event banners.',
    ],
    rows: ['emails', 'stories', 'phone', 'books', ['ramadan', 'earthday']],
  },
  {
    slug: 'naresco',
    title: 'Naresco Contracting',
    client: 'Naresco Contracting',
    field: 'Social media, print',
    sector: 'Construction',
    year: '2024–2026',
    cover: 'phone',
    summary: 'A consistent visual language for a contractor with a 40-year history.',
    body: [
      'I focused on building a consistent visual language across every touchpoint, from social media content to print. Whether it was technical graphics or marketing collateral, everything had to reflect Naresco’s long-standing reputation for quality.',
      'The occasion posts for Eid, Labour Day and National Day pair Arabic calligraphy with cranes and skylines drawn in the brand blue, so the greetings still look like a builder’s.',
    ],
    rows: ['phone', 'posts'],
  },
  {
    slug: 'proguard-renova360',
    title: 'ProGuard and ReNova360',
    client: 'ProGuard, ReNova360 Degrees',
    field: 'Print, social media, ads',
    sector: 'Property services',
    year: '2024–2026',
    cover: 'ads',
    summary: 'Company profiles, social content and paid ads for two property service brands.',
    body: [
      'I led the design of their core brand assets, most notably the company profiles, balancing technical detail with a clean, professional layout. Beyond print, I managed their ongoing visual presence with social media content and marketing collateral that stayed true to the new identity.',
      'ProGuard’s ads pair line-illustrated technicians with loud, single-colour backgrounds so each service reads at a glance in a feed, in English and Arabic.',
    ],
    rows: ['ads', 'posts', 'profiles', 'renova'],
  },
  {
    slug: 'daytona-properties',
    title: 'Daytona Properties',
    client: 'Daytona Properties',
    field: 'Social media ads, print',
    sector: 'Real estate',
    year: '2024–2026',
    cover: 'standee',
    summary: 'Ads, brochures and on-site signage for a Dubai real estate brokerage.',
    body: [
      'My day-to-day covered a wide range of assets, from social media ads and organic posts to brochures and marketing materials that buyers could hold in their hands.',
      'Keeping one sleek look across every touchpoint, navy, a classic serif and generous space, helped raise Daytona’s brand visibility and made sure their listings left a lasting impression online and on site.',
    ],
    rows: ['standee', 'ads', 'brochures'],
  },
  {
    slug: 'world-padel-academy',
    title: 'World Padel Academy',
    client: 'World Padel Academy',
    field: 'Social media',
    sector: 'Sports',
    year: '2024–2026',
    cover: 'posts',
    summary: 'Social media design support for a padel academy.',
    body: [
      'I designed a series of social media assets for their audience, keeping a steady flow of communication during my time on the project. Although my involvement was short term, I focused on clean, punchy designs that shared their expertise and updates with followers.',
    ],
    rows: ['posts'],
  },
  {
    slug: 'homega-heights',
    title: 'Homega Heights brochure',
    client: 'Homega Developments',
    field: 'Print, brochure',
    sector: 'Real estate',
    year: '2026',
    cover: 'mockup',
    summary: 'A premium brochure for a modern residential project in Dubai.',
    body: [
      'A folded brochure for Homega Heights, “Modern Living Redefined”. Warm stone and oxblood from the developer’s logo set the palette, and full-height renders give the architecture room to breathe, with a location map and key facts on the inside spread.',
    ],
    rows: ['mockup', ['cover', 'inside']],
  },
];
