// Site content. Each project becomes /work/<slug>.html and a row in the home page index.
// `cover` is the image used in the index preview; `rows` lay out the project page:
//   'name'            one full-width image
//   ['a', 'b']        two images side by side
//   { video, poster, ratio }   a looping muted clip
// Image names refer to assets/img/<slug>/<name>-<width>.webp (made by src/images.mjs).

export const SITE = {
  name: 'Carl Serafin',
  fullName: 'Carl Paolo Serafin',
  role: 'Graphic designer',
  city: 'Dubai',
  email: 'carlserafin02@gmail.com',
  whatsapp: '+971 55 150 2722',
  whatsappLink: 'https://wa.me/971551502722',
  behance: 'https://www.behance.net/carlserafin',
  url: 'https://cepsmyster.github.io/',
  description: 'Carl Paolo Serafin is a Dubai graphic designer making brand identities, company profiles, campaigns, presentations and websites for architecture, construction and real estate companies.',
};

export const ABOUT = {
  intro: [
    'I’m Carl Paolo Serafin, a graphic designer in Dubai. It started with a love of art. Now I turn it into work people use every day.',
    'Most of my clients build things: architecture firms, contractors and real estate developers across the UAE. I design their identities, company profiles, social campaigns, signage and presentations.',
    'Lately I’ve been building websites with Claude Code. The Top Concept International site was the first. I learn by shipping real pages for real clients.',
    'New team, new brief, tight deadline? I adapt fast. My favourite projects are the ones where one idea has to work on a phone screen, a printed page and a sign on a building.',
  ],
  fields: ['Brand identity', 'Print and editorial', 'Social media', 'Signage', 'Presentations', 'Motion graphics', 'Video editing', 'Web design and development'],
  tools: ['Illustrator', 'Photoshop', 'InDesign', 'After Effects', 'Premiere Pro', 'Figma', 'HTML, CSS and JavaScript'],
  languages: ['Filipino', 'English'],
};

export const PROJECTS = [
  {
    slug: 'top-concept-website',
    title: 'Website for an architecture and engineering consultancy',
    client: 'Top Concept International',
    field: 'Web design and development',
    sector: 'Architecture and engineering',
    year: '2026',
    cover: 'home',
    link: { href: 'https://cepsmyster.github.io/top-concept-website/', label: 'Visit the live site' },
    summary: 'My first website, designed and built for Top Concept International, an architecture and engineering consultancy in Dubai.',
    body: [
      'Drag the line on the home page and a blueprint becomes the finished tower. The headline draws itself in outline, then fills in: concept to completion, in one gesture.',
      'Behind it: a filterable archive with a page for every project, expertise, blogs, careers and contact forms, in light and dark themes. Plain HTML, CSS and JavaScript, hosted on GitHub Pages.',
    ],
    rows: ['home', ['mobile', 'projects'], 'expertise'],
  },
  {
    slug: 'tci-company-profile',
    title: 'Company profile and identity for an architecture group',
    client: 'Top Concept International',
    field: 'Brand identity, editorial',
    sector: 'Architecture and engineering',
    year: '2026',
    cover: 'front',
    summary: '108 pages for Top Concept International, and the identity system that holds them together.',
    body: [
      'Architecture, interiors and landscape each open on a full-bleed divider. Every project spread after it follows one grid of large and small renders, so a hundred pages read as one book.',
      'Underneath sits the identity: the TCi wordmark and folded-square mark, a palette of greys, Montserrat and Inter. It carries through to business cards, wall signage, folders, pens and mugs.',
    ],
    rows: ['front', 'cover', ['divider', 'interiors'], 'azizi', ['hospitality', 'rox'], 'lobby', ['interiors2', 'landscape'], 'marks', 'identity'],
  },
  {
    slug: 'touch-id-contracting',
    title: 'Brand identity for a contracting company',
    client: 'Touch ID Contracting',
    field: 'Brand identity',
    sector: 'Construction',
    year: '2026',
    cover: 'logo',
    summary: 'Two identities for Touch ID Contracting in Dubai: the touch id wordmark and the TID monogram.',
    body: [
      'There’s a fingerprint hidden in the o. The touch id wordmark comes in cinnamon orange with a striped barrier-tape pattern, and runs across business cards, building signage, company cars, buses, mugs and safety vests.',
      'TID boils the name down to a boxed monogram in charcoal and bronze, made for the places a contractor’s name is seen most: uniforms, overalls, helmets, staff IDs and the site bus. One line ties both together: building with precision, delivering with confidence.',
    ],
    rows: ['logo', ['mark', 'pattern'], 'cards', ['signage', 'vest'], 'cars', 'bus', 'tid', ['tidcolors', 'tidcards'], ['tidshirt', 'tidhelmet'], 'tidoveralls', ['tidid', 'tidbus']],
  },
  {
    slug: 'ips-2026',
    title: 'Exhibition campaign for a group of companies',
    client: 'The Top Group',
    field: 'Social media, motion, video and photo coverage',
    sector: 'Exhibition',
    year: '2026',
    cover: 'countdown',
    summary: 'Countdown stories, video and photo coverage for The Top Group at IPS 2026, Dubai World Trade Centre.',
    body: [
      'Each countdown story keeps to three things: one big number, the dates and the booth. Every company in the group signs off underneath: TCI, TCI Interiors, TCI Landscape, X30 Technical, Touch ID Decorations and TID Contracting.',
      'At the show I filmed and photographed the stand, the meetings in the lounge, the tower model and the live violinist, then cut it all into a vertical recap for social media. On the stand, the backdrop video cycled through project sheets from across the group.',
    ],
    rows: [{ video: 'ips-backdrop', ratio: '16 / 9' }, ['countdown', { video: 'ips-recap', ratio: '9 / 16' }]],
  },
  {
    slug: 'resort-concept',
    title: 'Concept design presentation for a forest resort',
    client: 'Top Concept International',
    field: 'Presentation design',
    sector: 'Hospitality',
    year: '2026',
    cover: 'cover',
    summary: '74 slides that walk a client through a forest resort in India, made at Top Concept International.',
    body: [
      'It starts with the master plan: suites strung along a winding lagoon. Then one building at a time: amenities, restaurant and banquet, clubhouse, health club and suites. Each gets a colour-coded floor plan first, then the 3D concept views.',
      'Material boards of tent fabric, natural wood, mud plaster and sandstone tie the renders together. A quiet stone-grey layout with small headers lets the warm interiors carry every slide.',
    ],
    rows: ['cover', 'master', ['amenities', 'pool'], 'reception', ['dining', 'lobby'], 'plan', ['cards', 'arcade'], 'jacuzzi', ['suiteboard', 'suites']],
  },
  {
    slug: 'villa-estate-presentation',
    title: 'Design and technical presentation for a private villa estate',
    client: 'Top Concept International',
    field: 'Presentation design',
    sector: 'Residential',
    year: '2026',
    cover: 'mansion',
    summary: 'From the site to the cost in one deck: a design and technical presentation for a waterfront villa estate, made at Top Concept International.',
    body: [
      'Project overview, schematic drawings, 3D renders of the main mansion and outdoor majlis, interior moodboards, then the timeline, cash flow and bill of quantities. The client never has to open a second file.',
      'The renders run full width under a thin header, so the stone and the formal gardens read at full size. For the interiors, the moodboards switch to a darker, editorial layout.',
    ],
    rows: ['aerial', ['mansion', 'garden'], 'beach', 'majlis', ['bedroom', 'bathroom']],
  },
  {
    slug: 'fitout-company-profile',
    title: 'Company profile for an interior fit-out company',
    client: 'Top Concept International',
    field: 'Editorial, presentation design',
    sector: 'Interior fit-out and joinery',
    year: '2026',
    cover: 'government',
    summary: '79 pages for a Dubai fit-out and joinery company in the group, made at Top Concept International.',
    body: [
      'After the about, vision and services pages, the work is sorted by sector: government, residential towers, offices, food and beverage, retail and landscape. Each sector opens on a full-width photo, a bold yellow headline and a short list of notable projects.',
      'The spreads that follow pair one large photo with a grid of smaller ones and a yellow caption block. Close to eighty pages, one rhythm.',
    ],
    rows: ['cover', ['about', 'vision'], 'government', ['residential', 'office'], 'fnb', ['retail', 'landscape']],
  },
  {
    slug: 'repc-signage',
    title: 'Storefront signage for a polyclinic academy',
    client: 'Royal European Polyclinic Academy',
    field: 'Signage, print',
    sector: 'Healthcare and beauty',
    year: '2026',
    cover: 'navy',
    summary: 'Opening soon and grand opening signage for the new storefront of Royal European Polyclinic Academy.',
    body: [
      'Two directions for the hoarding. One light, with script lettering and the treatment device as the hero. One deep navy, built on close-up treatment photography.',
      'I mocked both up on a photo of the actual storefront, so the client could see them in place before anything went to print.',
    ],
    rows: ['navy', ['grand', 'soon'], 'navy2', 'site'],
  },
  {
    slug: 'abdulla-al-arif',
    title: 'Brand system for a diversified group',
    client: 'Abdulla Al Arif Investments',
    field: 'Brand system, digital, print',
    sector: 'Diversified industrial group',
    year: '2024–2026',
    cover: 'emails',
    summary: 'One visual identity for Abdulla Al Arif Investments, across a group of construction, real estate and service companies.',
    body: [
      'Many companies, one look. I built a design system that keeps the AAAI Group consistent while letting each subsidiary show its own strengths.',
      'It covers exhibition stands and print for milestones like the Annual Gathering Iftar, internal email campaigns, Instagram stories, magazines, posters and event banners.',
    ],
    rows: ['emails', 'stories', 'phone', 'books', ['ramadan', 'earthday']],
  },
  {
    slug: 'naresco',
    title: 'Social media and print for a contractor',
    client: 'Naresco Contracting',
    field: 'Social media, print',
    sector: 'Construction',
    year: '2024–2026',
    cover: 'posts',
    summary: 'A consistent visual language for Naresco Contracting, a contractor with a 40-year history.',
    body: [
      'Forty years of reputation sets a high bar. From technical graphics to marketing collateral, every piece had to look as solid as the company behind it.',
      'The occasion posts for Eid Al Adha and the Islamic New Year pair Arabic calligraphy with cranes and city skylines drawn in the brand blue. Greetings that still look like a builder’s.',
    ],
    rows: ['posts'],
  },
  {
    slug: 'proguard-renova360',
    title: 'Print, social and ads for two property service brands',
    client: 'ProGuard, ReNova360 Degrees',
    field: 'Print, social media, ads',
    sector: 'Property services',
    year: '2024–2026',
    cover: 'stories',
    summary: 'Company profiles, social content and paid ads for two property service brands, ProGuard and ReNova360 Degrees.',
    body: [
      'I led the core brand assets, starting with the company profiles: technical detail, laid out cleanly. Then the everyday work: social media content and marketing collateral, all true to the new identity.',
      'ProGuard’s ads pair line-illustrated technicians with loud, single-colour backgrounds, so each service reads at a glance in a feed, in English and Arabic.',
    ],
    rows: ['stories', 'posts', 'profiles', 'renova'],
  },
  {
    slug: 'daytona-properties',
    title: 'Ads and brochures for a real estate brokerage',
    client: 'Daytona Properties',
    field: 'Print, social media ads',
    sector: 'Real estate',
    year: '2024–2026',
    cover: 'valoura',
    summary: 'A leasing brochure, ads and stories for Daytona Properties, a Dubai real estate brokerage.',
    body: [
      'Valoura Residences, a new building in Nad Al Sheba that Daytona manages, needed a brochure. Six pages take a tenant from the cover to the inquiry form: location and drive times, the building, unit types from studios to two-bedroom apartments, and the amenities, closing on a QR code to book a viewing.',
      'Day to day, I made the ads and stories that bring buyers in: launches like Binghatti Skyhall and DAMAC Islands, and a series that asks investors whether their returns come from real data. Navy, a classic serif and generous space keep it all recognisably Daytona.',
    ],
    rows: ['valoura', 'pages', 'posts', 'stories'],
  },
  {
    slug: 'world-padel-academy',
    title: 'Social media for a padel academy',
    client: 'World Padel Academy',
    field: 'Social media',
    sector: 'Sports',
    year: '2024–2026',
    cover: 'posts',
    summary: 'Social media design for World Padel Academy.',
    body: [
      'A short project with one job: keep the academy’s feed moving. I designed clean, punchy posts that shared their coaching know-how and updates with followers.',
    ],
    rows: ['posts'],
  },
  {
    slug: 'homega-heights',
    title: 'Brochure for a residential development',
    client: 'Homega Developments',
    field: 'Print, brochure',
    sector: 'Real estate',
    year: '2026',
    cover: 'mockup',
    summary: 'A premium brochure for Homega Heights, a modern residential project in Dubai by Homega Developments.',
    body: [
      '“Modern Living Redefined.” Warm stone and oxblood from the developer’s logo set the palette. Full-height renders give the architecture room to breathe, with a location map and key facts on the inside spread.',
    ],
    rows: ['mockup', ['cover', 'inside']],
  },
];
